create table exchange_rate (
    id bigint generated by default as identity primary key,
    currency_code varchar(255) not null,
    deal_bas_rate numeric(12, 2) not null,
    base_date date not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_exchange_rate_currency_date unique (currency_code, base_date)
);

create index idx_exchange_rate_base_date on exchange_rate (base_date);

create table category (
    id bigint generated by default as identity primary key,
    transaction_type varchar(10) not null,
    code varchar(50) not null,
    display_name varchar(100) not null,
    icon varchar(20),
    sort_order integer not null default 0,
    owner_member_id bigint not null default 0,
    is_active boolean not null default true,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_category_owner_type_code unique (owner_member_id, transaction_type, code)
);

create index idx_category_owner_type on category (owner_member_id, transaction_type);

create table asset (
    id bigint generated by default as identity primary key,
    code varchar(50) not null,
    display_name varchar(100) not null,
    icon varchar(20),
    sort_order integer not null default 0,
    owner_member_id bigint not null default 0,
    is_active boolean not null default true,
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint uk_asset_owner_code unique (owner_member_id, code)
);

create table ledger_entry (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    transaction_type varchar(10) not null,
    category_id bigint not null,
    asset_id bigint not null,
    original_amount numeric(15, 2) not null,
    currency_code varchar(10) not null,
    applied_rate numeric(12, 2) not null,
    rate_base_date date,
    krw_amount numeric(15, 2) not null,
    transaction_date date not null,
    memo varchar(255),
    created_at timestamp(6),
    updated_at timestamp(6),
    constraint fk_ledger_category foreign key (category_id) references category (id),
    constraint fk_ledger_asset foreign key (asset_id) references asset (id)
);

create index idx_ledger_member_date on ledger_entry (member_id, transaction_date);
